### ISSUE TITLE
Path function

### ISSUE THREAD

**Issue by zyayaa** [kennygrant/sanitize#20]
Path function is dealing correctly with this vector "http://localhost:8080/?file=..\etc/passwd" but when you use "http://localhost:8080/?file=../etc/passwd" the result path will be "/etc/passwd"

**Comment by kennygrant** [comment]
Sorry for the late response, life got in the way. This function isn't intended to serve files, and cannot know. I've improved the docs to make this clear though. 

If you're serving files you should *always* clean the path but also always root the path at a known root (say your public folder). On its own this function doesn't serve files and isn't intended to prefix them with a known safe path, it simply strips accents, .. and calls path.Clean on the path. 

If you clean it with path.Clean or a function such as this, you then need to set the root (be that "." or "./public" or "./public/assets" before calling functions to stat the file or read it. 

If you have an example of bad usage please do let me know though.
